/**
 * app.js
 * App-level utilities: PDF export.
 * Sidebar logic lives entirely in nav.js.
 */

import { getData } from './storageService.js';
import { getAppSettings } from './config.js';
import { getToday } from './utils.js';

/* ─────────────────────────────────────
   PDF / PRINT REPORT EXPORT
───────────────────────────────────── */
export function exportToPDF() {
    const user  = getData("currentUser", {});
    const name  = user.name || "User";
    const today = getToday().toLocaleDateString("en-GB", {
        weekday: "long", day: "2-digit", month: "long", year: "numeric"
    });

    const habitsKey = "habits_" + (user.email || "guest");
    const habitList = getData(habitsKey, []);
    const { xpPerCompletion, levelXpThreshold } = getAppSettings();

    const totalXP   = habitList.reduce((s, h) => s + (h.completedDates || []).length * xpPerCompletion, 0);
    const level     = Math.floor(totalXP / levelXpThreshold) + 1;
    const bestStreak = habitList.reduce((s, h) => Math.max(s, h.streak || 0), 0);
    const totalDone  = habitList.reduce((s, h) => s + (h.completedDates || []).length, 0);

    const habitRows = habitList.map(h => {
        const done = (h.completedDates || []).length;
        const rate = done > 0 ? Math.min(100, Math.round((done / 7) * 100)) : 0;
        const priColor = h.priority === "High"   ? "#ef4444"
                       : h.priority === "Medium" ? "#eab308"
                       : h.priority === "Low"    ? "#22c55e" : "#94a3b8";
        return `<tr>
            <td>${h.name}</td>
            <td>${h.category || "-"}</td>
            <td>${h.period || "Daily"}</td>
            <td style="color:${priColor};font-weight:600;">${h.priority || "-"}</td>
            <td>${h.streak || 0} days</td>
            <td>${done} times</td>
            <td>
                <div style="background:#e2e8f0;border-radius:4px;height:8px;width:80px;display:inline-block;vertical-align:middle;">
                    <div style="background:#6366f1;border-radius:4px;height:8px;width:${rate}%;"></div>
                </div> ${rate}%
            </td>
        </tr>`;
    }).join("") || `<tr><td colspan="7" style="text-align:center;color:#94a3b8;">No habits yet.</td></tr>`;

    const css = `
        body{font-family:Arial,sans-serif;background:#f8fafc;color:#1e293b;margin:0;padding:0;}
        .cover{background:linear-gradient(135deg,#1e1b4b,#312e81);color:#fff;padding:60px 50px;}
        .cover h1{font-size:36px;margin:0 0 8px;}
        .cover p{font-size:14px;opacity:.7;margin:4px 0;}
        .stats-row{display:flex;gap:20px;margin-top:36px;flex-wrap:wrap;}
        .stat{background:rgba(255,255,255,.12);border-radius:12px;padding:18px 24px;text-align:center;min-width:100px;}
        .stat .num{font-size:28px;font-weight:700;font-family:monospace;}
        .stat .lbl{font-size:11px;opacity:.7;margin-top:4px;}
        .section{padding:40px 50px;}
        .section h2{font-size:20px;font-weight:700;margin-bottom:20px;color:#1e293b;border-bottom:2px solid #6366f1;padding-bottom:10px;}
        table{width:100%;border-collapse:collapse;font-size:13px;}
        th{background:#1e1b4b;color:#fff;padding:10px 14px;text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:.05em;}
        td{padding:10px 14px;border-bottom:1px solid #e2e8f0;}
        tr:nth-child(even) td{background:#f1f5f9;}
        .footer{text-align:center;padding:28px;color:#94a3b8;font-size:12px;border-top:1px solid #e2e8f0;}`;

    const reportHTML = `<!DOCTYPE html><html><head><meta charset="UTF-8">
        <title>PPS Report - ${name}</title><style>${css}</style></head><body>
        <div class="cover">
            <p style="font-size:11px;letter-spacing:.1em;opacity:.6;text-transform:uppercase;">Personal Performance System</p>
            <h1>Performance Report</h1>
            <p style="font-size:18px;margin-top:8px;">User: ${name}</p>
            <p>${today}</p>
            <div class="stats-row">
                <div class="stat"><div class="num">${level}</div><div class="lbl">Level</div></div>
                <div class="stat"><div class="num">${totalXP}</div><div class="lbl">Total XP</div></div>
                <div class="stat"><div class="num">${bestStreak}</div><div class="lbl">Best Streak</div></div>
                <div class="stat"><div class="num">${totalDone}</div><div class="lbl">Completions</div></div>
                <div class="stat"><div class="num">${habitList.length}</div><div class="lbl">Habits</div></div>
            </div>
        </div>
        <div class="section">
            <h2>Habit Details</h2>
            <table><thead><tr>
                <th>Habit</th><th>Category</th><th>Period</th><th>Priority</th>
                <th>Streak</th><th>Completions</th><th>Success Rate</th>
            </tr></thead><tbody>${habitRows}</tbody></table>
        </div>
        <div class="footer">Generated by PPS — Personal Performance System | ${today}</div>
        </body></html>`;

    try {
        const win = window.open("", "_blank");
        if (!win) throw new Error("popup blocked");
        win.document.open();
        win.document.write(reportHTML);
        win.document.close();
        setTimeout(() => { win.focus(); win.print(); }, 800);
    } catch {
        const blob = new Blob([reportHTML], { type: "text/html" });
        const url  = URL.createObjectURL(blob);
        const a    = document.createElement("a");
        a.href = url; a.download = "PPS_Report.html"; a.click();
        URL.revokeObjectURL(url);
    }
}
